version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: user-cache-postgres
    environment:
      POSTGRES_DB: user_cache_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user-cache-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: user-cache-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - user-cache-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis-data:

networks:
  user-cache-network:
    driver: bridge